GerenciadorTarefas/urls.py
from django.contrib import admin
from django.urls import path, include
from app.views.tarefas_views import index
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tarefas/', include(('app.urls','app'), namespace='app')),
    path('home/', index, name="home"),
    path('', index, name="index"),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

app/urls.py
from django.contrib import admin
from django.urls import path
from .views.tarefas_views import *
from .views.usuarios_views import *


urlpatternsuser = [
    path('cadastrar-usuario/', cadastrar_usuario, name="cadastrar_usuario"),
    path('logar-usuario/', logar_usuario, name="logar_usuario"),
    path('deslogar-usuario/', deslogar_usuario, name="deslogar_usuario"),
]

urlpatterns = [
    path('listar/', listar_tarefas, name="listar_tarefas"),
    path('publicas/', listar_publicas, name="tarefas_publicas"),
    path('cadastrar/', cadastrar_tarefas, name="cadastrar_tarefas"),
    path('editar/<int:id>/', editar_tarefas, name="editar_tarefas"),
    path('remover/<int:id>/', remover_tarefas, name="remover_tarefas"),
    
] 
urlpatterns += urlpatternsuser

app/models.py
from django.db import models
from django.contrib.auth.models import User

class Tarefa(models.Model):
    PRIORIDADE_CHOICES = [
        ('A', "Alta"),
        ('N', "Normal"),
        ('B', "Baixa"),

    ]
    titulo = models.CharField(max_length=30, null=False, blank=False)
    public = models.BooleanField(default=False)
    descricao = models.CharField(max_length=100, null=False, blank=False)
    data_expiracao = models.DateField(null=False, blank=False)
    prioridade = models.CharField(max_length=1, choices=PRIORIDADE_CHOICES, null=False, blank=False)
    usuario = models.ForeignKey(User, null=True, on_delete=models.CASCADE )

app/forms.py
from django import forms
from .models import Tarefa


class TarefaForm(forms.ModelForm):
    class Meta:
        model = Tarefa
        fields = ['titulo','descricao','data_expiracao','public','prioridade']

app/views/tarefas_views.py
from django.shortcuts import render,redirect
from ..forms import TarefaForm
from django.contrib.auth.models import User
from ..services import tarefa_service
from django.contrib.auth.decorators import login_required
from ..models import Tarefa


def index(request):
    return render(request, 'index.html')


def listar_publicas(request):
    tarefas = Tarefa.objects.filter(public=True)
    return render(request, 'tarefas/tarefas_publicas.html', {'tarefas': tarefas})


@login_required
def listar_tarefas(request):
    usuario_logado  = request.user.id
    tarefas = tarefa_service.listar_tarefas(usuario_logado)
    return render(request, 'tarefas/listar_tarefas.html',{'tarefas':tarefas})

@login_required
def cadastrar_tarefas(request):
    if request.method == 'POST':
        form_tarefa = TarefaForm(request.POST)
        if form_tarefa.is_valid():

            form_tarefa_save = form_tarefa.save(commit=False)
            user = User.objects.get(id=request.user.id)
            form_tarefa_save.usuario = user
            form_tarefa_save.save()
            return redirect('app:listar_tarefas')

    else:
        form_tarefa = TarefaForm()
    return render(request, 'tarefas/form_tarefa.html',{'form_tarefa':form_tarefa})

@login_required
def editar_tarefas(request, id):
    usuario_logado  = request.user.id
    tarefa_especifica = tarefa_service.listar_tarefas_id(id,usuario_logado)
    form_tarefa = TarefaForm(request.POST or None, instance=tarefa_especifica)
    if request.method == 'POST':
        if form_tarefa.is_valid():
            form_tarefa.save()
            return redirect('app:listar_tarefas')
        else:
            redirect('app:editar_tarefas')
    return render(request, 'tarefas/form_tarefa.html', {'form_tarefa':form_tarefa})

@login_required
def remover_tarefas(request, id):
    usuario_logado  = request.user.id
    tarefa_especifica = tarefa_service.listar_tarefas_id(id,usuario_logado)
    if request.method == 'POST':
        tarefa_service.deletar_tarefa(tarefa_especifica,usuario_logado)
        return redirect ('app:listar_tarefas')
    return render(request, 'tarefas/confirma_exclusao.html',{'tarefa':tarefa_especifica })

app/views/usuarios_views.py
from django.shortcuts import render,redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages


def cadastrar_usuario(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('app:listar_tarefas')
    else:
        form = UserCreationForm()
    return render(request, 'usuarios/form_usuario.html', {'form':form})

def logar_usuario(request):
    if request.method == 'POST':
        username = request.POST['username']
        paswd = request.POST['password']
        usuario = authenticate(request, username=username, password=paswd)
        if usuario is not None:
            login(request, usuario)
            return redirect('app:listar_tarefas')
        else:
            messages.error(request, 'As credências estão incorretas!')
            return redirect('app:logar_usuario')


    login_form = AuthenticationForm()
    return render(request, 'usuarios/form_login.html', {'form_login':login_form})

def deslogar_usuario(request):
    logout(request)
    return redirect('app:logar_usuario')

app/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="pt-br">

<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" type="text/css" href="{% static 'app/css/bootstrap.min.css' %}">
	<title>Gerenciador de Tarefas - Listar Tarefas</title>
</head>

<body>
	<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
		<a class="navbar-brand" href="/">Manager</a>
		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
			aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		</button>
		<div class="collapse navbar-collapse" id="navbarNav">
			<ul class="navbar-nav">
				<li class="nav-item active">
					<a class="nav-link" href="{% url 'app:listar_tarefas'%}">Tarefas</a>
				</li>
				{% if user.authenticated %}
					<li class="nav-item active">
						<a class="nav-link" href="{% url 'app:deslogar_usuario'%}">Sair</a>
					</li>
				{% endif %}
			</ul>
		</div>
	</nav>
	<main class="container">
		{% block content %}

		{% endblock %}
	</main>
	<script src="https://code.jquery.com/jquery-3.5.1.min.js"
		integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" type="text/js" crossorigin="anonymous"></script>
	<script src="{% static 'app/js/bootstrap.min.js' %}" type="text/js" ></script>

</body>

</html>

app/templates/index.html
{% load static %}
<!doctype html>
<html lang="pt-br">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<meta name="description" content="Ruan Pablo's Manager">
	<meta name="author" content="Ruan Pablo's Manager">
	<title>Gerenciador de Tarefas by Ruan</title>

	<!-- Bootstrap core CSS -->
	<link href="{% static 'app/css/bootstrap.min.css' %}" type="text/css" rel="stylesheet">
	<link href="{% static 'app/css/cover.css' %}" type="text/css" rel="stylesheet">
</head>

<body class="text-center">

	<div class="cover-container d-flex h-100 p-3 mx-auto flex-column">
		<header class="masthead mb-auto">
			<div class="inner">
				<h3 class="masthead-brand">Manager</h3>
				<nav class="nav nav-masthead justify-content-center">
					<a class="nav-link active" href="/">Home</a>
					<a class="nav-link" href="{% url 'app:tarefas_publicas' %}">Tasks Public</a>
					{% if user.is_authenticated %}
						<a class="nav-link" href="{% url 'app:deslogar_usuario' %}">Logout</a>
					{% else %}
						<a class="nav-link" href="{% url 'app:cadastrar_usuario' %}">Register</a>
					{% endif %}
				</nav>
			</div>
		</header>

		<main role="main" class="inner cover">
			<h1 class="cover-heading">Seja organizado(a).</h1>
			<p class="lead">O meu antigo problema de organização se tranformou nesse site. Compartilho com vocês a minha
				solução em forma de site</p>
			<p class="lead">
				<a href="{% url 'app:cadastrar_usuario' %}" class="btn btn-lg btn-secondary">Register</a>
			</p>
		</main>

		<footer class="mastfoot mt-auto">
			<div class="inner">
				<p>Template for <a  href="https://getbootstrap.com/" target="about:blank">Bootstrap</a>, by <a
						href="https://twitter.com/mdo" target="about:blank">@mdo</a>.</p>
			</div>
		</footer>
	</div>
	<!-- Bootstrap core JavaScript
    ================================================== -->
	<!-- Placed at the end of the document so the pages load faster -->
	<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
		integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
		crossorigin="anonymous" type="text/js"></script>
	<script src="{% static 'app/assets/js/vendor/popper.min.js' %}"type="text/js"></script>
	<script src="{% static 'app/dist/js/bootstrap.min.js' %}" type="text/js"></script>
</body>

</html>

app/templates/tarefas/confirma_exclusao.html
{% extends 'base.html' %}

{% block content %}
    <h1 class="text-center p-3">
        Confirmação de exclusão
    </h1>
    <div class="card mb-3">
        <div class="card-header">
            Tem certeza que deseja remover essa tarefa?
        </div>
        <div class="card-body">
            <h5 class="card-titile">{{ tarefa.titulo }}</h5>
            <p class="card-text">{{ tarefa.descricao }}</p>
            <hr>
            <form method="post">
                {% csrf_token %}
                <button class="btn btn-danger" type="submit">Remover</button>
            </form>
        </div>
    </div>
{% endblock %}

app/templates/tarefas/form_tarefa.html
{% extends 'base.html' %}
{% load boot_css %}
{% block content %}
    <h1 class="text-center p-3">Cadastrar nova tarefa</h1>
    <form  method="POST">
        {% csrf_token %}
        <div class="form-group">
            {{ form_tarefa.titulo.errors }}
            <label>Título :</label>
            {{ form_tarefa.titulo|addClass:'form-control' }}
        </div>
        <div class="form-group">
            {{ form_tarefa.descricao.errors }}
            <label>Descrição :</label>
            {{ form_tarefa.descricao|addClass:'form-control' }}
        </div>
        <div class="form-group">
            {{ form_tarefa.data_expiracao.errors }}
            <label>Data de expiração :</label>
            {{ form_tarefa.data_expiracao|addClass:'form-control' }}
        </div>
        <div class="form-group">
            {{ form_tarefa.public.errors }}
            <label>Pública :</label>
            {{ form_tarefa.public }}
        </div>
        <div class="form-group">
            {{ form_tarefa.prioridade.errors }}
            <label>Prioridade :</label>
            {{ form_tarefa.prioridade|addClass:'form-control' }}
        </div>
        <div class="form-group">
            <input type="submit" value="Enviar"/>
        </div>
    </form>
{% endblock %}

app/templates/tarefas/listar_tarefas.html
{% extends 'base.html' %}
{% block content %}
	<h1 class="text-center p-3">Listagem de Tarefas</h1> 

	{% for tarefa in tarefas %}
	<div class="card mb-3">
		<div class="card-header">
			{{ tarefa.get_prioridade_display }}
		</div>
		<div class="card-body">
			<h5 class="card-titile">{{ tarefa.titulo }}</h5>
			<p class="card-text">{{ tarefa.descricao }}</p>
			<p class="card-text">by {{ tarefa.usuario }}</p>
			<hr>
			<a href="{% url 'app:editar_tarefas' tarefa.id %}" class="p-3">Alterar tarefa</a>
			<a href="{% url 'app:remover_tarefas' tarefa.id %}"class="md-3 btn btn-danger">Remover tarefa</a>
		</div>
	</div>
	{% endfor %}
	<a href="{% url 'app:cadastrar_tarefas' %}"><input type="button" class="btn btn-primary" value="Cadastrar Nova Tarefa"></a>
{% endblock %}

app/templates/tarefas/tarefas_publicas.html
{% extends 'base.html' %}

{% block content %}
    {% if tarefas %}
        <h1 class="text-center p-3">Tarefas Públicas</h1> 
        {% for tarefa in tarefas %}
        <div class="card mb-3">
            <div class="card-header">
                {{ tarefa.get_prioridade_display }}
            </div>
            <div class="card-body">
                <h5 class="card-titile">{{ tarefa.titulo }}</h5>
                <p class="card-text">{{ tarefa.descricao }}</p>
                <p class="card-text">by {{ tarefa.usuario }}</p>
            </div>
        </div>
        {% endfor %}
    {% else %}
        <h1 class="text-center p-3">Não há tarefas públicas</h1> 
    {% endif %}
{% endblock %}

app/templates/usuarios/form_login.html
{% extends 'base.html' %}
{% load boot_css %}
{% block content %}
    
    <h1 class="text-center p-3">Login</h1>
    <form method="post">
        {% csrf_token %}
        {% for message in messages %}
            <div class="alert alert-danger">
                {{ message }}
            </div>
        {% endfor %}
        <div class="form-group">
            {{form_login.username.errors}}
            <label>Nome de usuário:</label>
            {{form_login.username|addClass:'form-control'}}
        </div>
        <div class="form-group">
            {{form_login.password1.errors}}
            <label>Senha:</label>
            {{form_login.password|addClass:'form-control'}}
        </div>
        
        <div class="form-group">
            <input type="submit" class="btn btn-primary" value="Logar">
        </div>

    </form>
{% endblock %}

app/templates/usuarios/form_usuario.html
{% extends 'base.html' %}
{% load boot_css %}
{% block content %}
    <h1 class="text-center p-3">Cadastro de usuários</h1>
    <form method="post" class="p-3">
        {% csrf_token %}
        <div class="form-group">
            {{form.username.errors}}
            <label>Nome de usuário:</label>
            {{form.username|addClass:'form-control'}}
        </div>
        <div class="form-group">
            {{form.password1.errors}}
            <label>Senha:</label>
            {{form.password1|addClass:'form-control'}}
        </div>
        <div class="form-group">
            {{form.password2.errors}}
            <label>Confirmação de senha:</label> 
            {{form.password2|addClass:'form-control'}}
        </div>
        <div class="form-group">
            <input type="submit" class="btn btn-primary" value="Cadastrar">
        </div>
    </form>
{% endblock %}